import Header from "@/components/header"
import "../styles/globals.css"
import { ThemeProvider } from "@/components/themeProvider"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
        attribute="class" 
        defaultTheme="system" 
        enableSystem
        >
          <Header />
          <div className='px-4 lg:px-2'>

            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
